In [1]:
# Needed libraries 

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.actions.action_builder import ActionBuilder
from selenium.webdriver.common.actions.key_input import KeyInput
from selenium.webdriver.common.actions.pointer_input import PointerInput
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service


import undetected_chromedriver as uc
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait



# System requiremenmts 
import time
import random
import datetime as dt
import os 

# Data Management 
import pandas as pd


# Parameters 
URL_CHARGERS = "https://www.tesla.com/findus/list/chargers/Mexico"
URL_SUPERCHARGERS = "https://www.tesla.com/findus/list/superchargers/Mexico"

In [2]:
EMAIL = os.getenv("OSM_EMAIL")

In [7]:
df

,location_label,description,charger_type
0,Fiesta Americana Aguascalientes,"Calle Los Laureles S/N Las Flores, Aguascalien...",charger
1,Fiesta Inn Aguascalientes,Calle Mahatma Gandhi #302 Sur Prados de Villas...,charger
2,One Aguascalientes San Marcos,"Los Laureles No. 404 Fracc. Las Flores, Aguasc...",charger
3,Adobe Guadalupe,"Parcela A-1 s/n Rusa de Guadalupe, Ensenada, B...",charger
4,Bajamar,"Ensenada, Carretera Tijuana - Ensenada Km. 77....",charger
...,...,...,...
28,"Cancún, QRO","SM 46 Carr. Cancún, Cancun, Querétaro 77560",super_charger
29,"Matehuala, SLP","57 Tramo Matehuala-Saltillo KM. 11 + 385.49, M...",super_charger
30,"Villa Hidalgo, SLP","78973 Villa de Hidalgo, San Luis Potosi, Villa...",super_charger
31,"Santa Ana, SON","901 5 de Mayo, La Loma, Santa Ana, Sonora 84600",super_charger
32,"Valladolid, YUC","KM 152+700 Autopista Mérida-Cancún, Valladolid...",super_charger

In [8]:
df_superchargers.head(3)

,location_label,description,charger_type
0,"Aguascalientes, AGS","Km. 11 Carr. Panamericana, Aguascalientes, Agu...",super_charger
1,"Ensenada, BCS","Km.103 #3421 Zona Playitas, Ensenada, Baja Cal...",super_charger
2,"Chihuahua, CH","5915 Perif. de la Juventud, Chihuahua, Chihuah...",super_charger

In [9]:
df_chargers.loc[2,"description"]

'Los Laureles No. 404 Fracc. Las Flores, Aguascalientes., AGU 20220'

In [10]:
df_superchargers.loc[1,"description"]

'Km.103 #3421 Zona Playitas, Ensenada, Baja California 22860'

In [11]:
import requests
import time

def get_coordinates_nominatim(address: str, email: str):
    """
    Given a text address, return (lat, lon) using Nominatim (OpenStreetMap)
    """
    url = "https://nominatim.openstreetmap.org/search"
    params = {
        "q": address,
        "format": "json",
        "limit": 1
    }

    headers = {
        "User-Agent": f"your-app-name/1.0 ({email})"
    }

    response = requests.get(url, params=params, headers=headers, timeout=10)
    response.raise_for_status()

    data = response.json()

    if not data:
        return None, None

    return float(data[0]["lat"]), float(data[0]["lon"])

In [13]:

df[["lat", "lon"]] = df["description"].apply(
    lambda x: pd.Series(get_coordinates_nominatim(x,EMAIL ))
)

ReadTimeout: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=10)