In [7]:
# Needed libraries 


# System requiremenmts 
import time
import random
import datetime as dt
import os 

import requests
import time

# Data Management 
import pandas as pd


# Parameters 
URL_CHARGERS = "https://www.tesla.com/findus/list/chargers/Mexico"
URL_SUPERCHARGERS = "https://www.tesla.com/findus/list/superchargers/Mexico"

In [8]:
EMAIL = os.getenv("OSM_EMAIL")

In [9]:

def get_coordinates_nominatim(address: str, email: str):
    """
    Given a text address, return (lat, lon) using Nominatim (OpenStreetMap)
    """
    url = "https://nominatim.openstreetmap.org/search"
    params = {
        "q": address,
        "format": "json",
        "limit": 1
    }

    headers = {
        "User-Agent": f"your-app-name/1.0 ({email})"
    }

    response = requests.get(url, params=params, headers=headers, timeout=10)
    response.raise_for_status()

    data = response.json()

    if not data:
        return None, None

    return float(data[0]["lat"]), float(data[0]["lon"])

In [3]:
df = pd.read_csv("mexico_chargers_address.csv")

In [6]:
df.tail(3)

,location_label,description,charger_type
518,"Villa Hidalgo, SLP","78973 Villa de Hidalgo, San Luis Potosi, Villa...",super_charger
519,"Santa Ana, SON","901 5 de Mayo, La Loma, Santa Ana, Sonora 84600",super_charger
520,"Valladolid, YUC","KM 152+700 Autopista Mérida-Cancún, Valladolid...",super_charger

In [ ]:

def get_coordinates_nominatim(address: str, email: str):
    """
    Given a text address, return (lat, lon) using Nominatim (OpenStreetMap)
    """
    url = "https://nominatim.openstreetmap.org/search"
    params = {
        "q": address,
        "format": "json",
        "limit": 1
    }

    headers = {
        "User-Agent": f"your-app-name/1.0 ({email})"
    }

    

    response = requests.get(url, params=params, headers=headers, timeout=10)
    response.raise_for_status()

    data = response.json()

    if not data:
        return None, None

    return float(data[0]["lat"]), float(data[0]["lon"])

In [11]:

df[["lat", "lon"]] = df["description"].apply(
    lambda x: pd.Series(get_coordinates_nominatim(x,EMAIL))
)

In [15]:
df.dropna()

,location_label,description,charger_type,lat,lon
5,Bruma Valle de Guadalupe,Carretera Tecate Ensenada Km. 74 Valle de Guad...,charger,32.044643,-116.598636
9,Santuario Diegueño,"798 Río Yaqui, Tecate, Baja California 21420",charger,32.574437,-116.619099
10,Encuentro Guadalaupe,Carretera Tecate- Ensenada Km. 75 Valle de Gua...,charger,32.044643,-116.598636
11,Entre Santos Bodegas de Santo Tomas,Carretera Ensenada - Tecate Km. 94 San Antonio...,charger,31.967158,-116.659572
19,Hotel Las Rosas & Spa,Carretera Tijuana - Ensenada Km 105. 5 El Sauz...,charger,31.869921,-116.677012
...,...,...,...,...,...
505,"Mérida, YUC","185 Av. Andrés García Lavín, Merida, Yucatán 9...",super_charger,21.019552,-89.606556
511,"Cuernavaca, MOR","Km. 87.5 Tulipán Hawaiano, Cuernavaca, Morelos...",super_charger,18.935872,-99.193650
512,"San Pedro Garza Garcia, NL","555 Río Missouri, San Pedro Garza García, Nuev...",super_charger,25.664293,-100.374669
514,"San Francisco Ocotlán, PUE","Autopista México Puebla Km 115, San Francisco ...",super_charger,19.156220,-98.291894
518,"Villa Hidalgo, SLP","78973 Villa de Hidalgo, San Luis Potosi, Villa...",super_charger,22.451729,-100.676307

In [16]:
df.loc[5, "description"]

'Carretera Tecate Ensenada Km. 74 Valle de Guadalupe, Ensenada, Baja California 22760'